# Generated by Django 2.1.15 on 2020-05-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField(max_length=400)),
                ('OptionOne', models.CharField(max_length=20)),
                ('OptionTwo', models.CharField(max_length=20)),
                ('OptionThree', models.CharField(max_length=20)),
                ('OptionFour', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuizName', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('Questions', models.ManyToManyField(to='Quiz.QuestionModel')),
            ],
        ),
    ]
