# Generated by Django 2.1.15 on 2020-05-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='EmpEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='EmpGender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='EmpSalary',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='EmpName',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
