# Generated by Django 2.1.15 on 2020-05-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200520_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='EmpComp',
            field=models.CharField(choices=[('T', 'TATA'), ('E', 'EEEHUB'), ('I', 'ISRO')], max_length=10, null=True),
        ),
    ]
