# Generated by Django 2.1.15 on 2020-05-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accounts_empcomp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='EmpComp',
            field=models.CharField(choices=[('Tata', 'T'), ('EEEHUB', 'E'), ('ISRO', 'I')], max_length=10, null=True),
        ),
    ]
