# Generated by Django 2.1.15 on 2020-05-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200524_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='EmpLocation',
            field=models.CharField(choices=[('Katihar', 'Katihar'), ('Patna', 'Patna'), ('Mumbai', 'Mumbai')], max_length=10, null=True),
        ),
    ]
