# Generated by Django 2.1.15 on 2020-05-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0002_auto_20200518_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
    ]
