# Generated by Django 2.1.15 on 2020-05-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0003_auto_20200518_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
